Emzi0767.Web/Models/ErrorViewModel.cs
using System;

namespace Emzi0767.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Emzi0767.Web/Controllers/DiscordController.cs
using Emzi0767.Web.Configuration;
using Emzi0767.Web.Crypto;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;

namespace Emzi0767.Web.Controllers
{
    [Route("[controller]/[action]")]
    public class DiscordController : EmziControllerBase
    {
        public DiscordController(IOptions<ContentConfig> contentCfg, KeyManager keyManager) : base(contentCfg, keyManager) { }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet("{id?}")]
        public IActionResult CompanionCube(string id)
        {
            if (string.IsNullOrWhiteSpace(id))
                return View();
            else if (id.ToLower() == "doc")
                return View("CompanionCubeDoc");
            else if (id.ToLower() == "invite")
                return new RedirectResult("https://discordapp.com/oauth2/authorize?client_id=276042646693216258&scope=bot&permissions=0", true);
            else if (id.ToLower() == "source")
                return new RedirectResult("https://github.com/Emzi0767/Discord-Companion-Cube-Bot", true);
            return View();
        }

        [HttpGet("{id?}")]
        public IActionResult MusicTurret(string id)
        {
            if (string.IsNullOrWhiteSpace(id))
                return View();
            else if (id.ToLower() == "doc")
                return View("MusicTurretDoc");
            else if (id.ToLower() == "invite")
                return new RedirectResult("https://discordapp.com/oauth2/authorize?client_id=469727979614765066&scope=bot&permissions=0", true);
            else if (id.ToLower() == "source")
                return new RedirectResult("https://github.com/Emzi0767/Discord-Music-Turret-Bot", true);
            return View();
        }

        [HttpGet("{id?}")]
        public IActionResult Ada(string id)
        {
            if (string.IsNullOrWhiteSpace(id))
                return View();
            else if (id.ToLower() == "doc")
                return View("AdaDoc");
            //else if (id.ToLower() == "invite")
            //    return new RedirectResult("https://discordapp.com/oauth2/authorize?client_id=207900447044927488&scope=bot&permissions=2146958591", true);
            else if (id.ToLower() == "source")
                return new RedirectResult("https://github.com/Emzi0767/Discord-ADA-Bot", true);
            return View();
        }

        [HttpGet("{id?}")]
        public IActionResult Pam(string id)
        {
            if (string.IsNullOrWhiteSpace(id))
                return View();
            else if (id.ToLower() == "doc")
                return View("PamDoc");
            else if (id.ToLower() == "invite")
                return new RedirectResult("https://discordapp.com/oauth2/authorize?client_id=262603614890098689&scope=bot&permissions=2146958591", true);
            else if (id.ToLower() == "source")
                return new RedirectResult("https://github.com/Emzi0767/Discord-PAM-Bot", true);
            return View();
        }

        [HttpGet("{id?}")]
        public IActionResult Asm(string id)
        {
            if (string.IsNullOrWhiteSpace(id))
                return View();
            else if (id.ToLower() == "doc")
                return View("AsmDoc");
            else if (id.ToLower() == "invite")
                return new RedirectResult("https://discordapp.com/oauth2/authorize?client_id=283200903937261569&scope=bot&permissions=0", true);
            else if (id.ToLower() == "source")
                return new RedirectResult("https://github.com/Emzi0767/Discord-ASM-Bot", true);
            return View();
        }
    }
}

Emzi0767.Web/Controllers/HomeController.cs
using System.Diagnostics;
using Emzi0767.Web.Configuration;
using Emzi0767.Web.Crypto;
using Emzi0767.Web.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;

namespace Emzi0767.Web.Controllers
{
    public class HomeController : EmziControllerBase
    {
        public HomeController(IOptions<ContentConfig> contentCfg, KeyManager keyManager) : base(contentCfg, keyManager) { }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult About()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Emzi0767.Web/Controllers/ProjectsController.cs
using Emzi0767.Web.Configuration;
using Emzi0767.Web.Crypto;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;

namespace Emzi0767.Web.Controllers
{
    public class ProjectsController : EmziControllerBase
    {
        public ProjectsController(IOptions<ContentConfig> contentCfg, KeyManager keyManager) : base(contentCfg, keyManager) { }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult ClydeDotNet()
        {
            return View();
        }
    }
}

Emzi0767.Web/Controllers/UtilityController.cs
using System.Text;
using Emzi0767.Web.Configuration;
using Emzi0767.Web.Crypto;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using ZXing;
using ZXing.QrCode;
using ZXing.QrCode.Internal;

namespace Emzi0767.Web.Controllers
{
    [Route("api/util/[action]")]
    public class UtilityController : EmziControllerBase
    {
        private static UTF8Encoding UTF8 { get; } = new UTF8Encoding(false);

        public UtilityController(IOptions<ContentConfig> contentCfg, KeyManager keyManager) : base(contentCfg, keyManager) { }

        [HttpGet]
        public IActionResult Index()
        {
            return new BadRequestResult();
        }
        
        [ActionName("qr")]
        [HttpGet("{id}/{size:int=256}")]
        public IActionResult QRCode(string id, int size)
        {
            var zxsvg = new BarcodeWriterSvg
            {
                Format = BarcodeFormat.QR_CODE,
                Options = new QrCodeEncodingOptions
                {
                    ErrorCorrection = ErrorCorrectionLevel.L,
                    Width = size,
                    Height = size,
                    Margin = 1
                }  
            };
            var svg = zxsvg.Write(id.StringFromBase64()).ToString()
                .Replace("255,255,255", "17,17,17")
                .Replace("0,0,0", "221,221,221");

            return this.Content(svg, "image/svg+xml", UTF8);
        }

        [ActionName("test")]
        [HttpGet]
        public IActionResult TestOK()
        {
            return this.Content("Routing successful", "text/plain", UTF8);
        }
    }
}

Emzi0767.Web/Views/Discord/Ada.cshtml
@{
    ViewData["Title"] = "ADA";
    ViewData["og:title"] = "ADA";
    ViewData["og:description"] = "ADA (Automated/Advanced Discord Administrator) is designed to extend and simplify a number of administrative tasks.";
    ViewData["og:image"] = Url.FullContentUrl("~/images/discord/ada_v4_big.png");
    ViewData["content:center"] = true;
}

<img src="@Url.Content("~/images/discord/ada_v4.png")" alt="ADA" class="bot-image" />

<h1>ADA</h1>
<h3>Automated/Advanced Discord Administrator</h3>

<p>
    ADA (Automated/Advanced Discord Administrator) is designed to extend and simplify a number of administrative tasks. It's written in C#, using Discord.NET library. Currently pending porting to Clyde.NET. 
    ADA is a bot that simplifies and extends administration of Discord servers, adds some automated functionality, as well as some fun functionality. Initially designed as a bot for my server only, it has 
    since been rewritten and improved. 
</p>

<div class="margin">&nbsp;</div>

<div class="col-xs-12 col-md-4"><button title="Add to your server" class="btn btn-lg btn-primary" disabled="disabled">Add to your server</button></div>
<div class="col-xs-12 col-md-4"><a href="@Url.Action("Ada", new { id = "doc" })" title="Command documentation" class="btn btn-lg btn-default">Command documentation</a></div>
<div class="col-xs-12 col-md-4"><a href="@Url.Action("Ada", new { id = "source" })" target="_blank" title="View source on GitHub" class="btn btn-lg btn-default">View source on GitHub</a></div>

Emzi0767.Web/Views/Discord/AdaDoc.cshtml
@{
    ViewData["Title"] = "ADA Documentation";
    ViewData["og:title"] = "ADA Documentation";
    ViewData["og:description"] = "ADA (Automated/Advanced Discord Administrator) is designed to extend and simplify a number of administrative tasks.";
    ViewData["og:image"] = Url.FullContentUrl("~/images/discord/ada_v4_big.png");
    ViewData["content:center"] = true;
}

<img src="@Url.Content("~/images/discord/ada_v4.png")" alt="ADA" class="bot-image-small" />

<h1>ADA <small>- Documentation</small></h1>

<p>
    ADA is currently undergoing a complete rewrite. As a result, the command reference will drastically change in the coming versions.
</p>

Emzi0767.Web/Views/Discord/Asm.cshtml
@{
    ViewData["Title"] = "Assembler";
    ViewData["og:title"] = "Assembler";
    ViewData["og:description"] = "ASM (Assembler) is a bot that assembles assembly code to machine code, and outputs the resulting hex. Written using Discord.py library.";
    ViewData["og:image"] = Url.FullContentUrl("~/images/discord/asm_v2_big.png");
    ViewData["content:center"] = true;
}

<img src="@Url.Content("~/images/discord/asm_v2.png")" alt="ASM" class="bot-image" />

<h1>ASM</h1>
<h3>Assembler</h3>

<p>
    ASM (Assembler) is a bot that assembles assembly code to machine code, and outputs the resulting hex. Written using Discord.py library. ASM was designed as a very niche bot. It converts input assembly code 
    into machine code, and dumps its hex representation. It supports x86, x86_64, ARMv6, ARMv7, ARMv8, AArch64, MIPS, PowerPC, and PowerPC64 input. 
</p>

<div class="margin">&nbsp;</div>

<div class="col-xs-12 col-md-4"><a href="@Url.Action("Asm", new { id = "invite" })" target="_blank" title="Add to your server" class="btn btn-lg btn-primary">Add to your server</a></div>
<div class="col-xs-12 col-md-4"><a href="@Url.Action("Asm", new { id = "doc" })" title="Command documentation" class="btn btn-lg btn-default">Command documentation</a></div>
<div class="col-xs-12 col-md-4"><a href="@Url.Action("Asm", new { id = "source" })" target="_blank" title="View source on GitHub" class="btn btn-lg btn-default">View source on GitHub</a></div>

Emzi0767.Web/Views/Discord/AsmDoc.cshtml
@{
    ViewData["Title"] = "Assembler Documentation";
    ViewData["og:title"] = "Assembler Documentation";
    ViewData["og:description"] = "ASM (Assembler) is a bot that assembles assembly code to machine code, and outputs the resulting hex. Written using Discord.py library.";
    ViewData["og:image"] = Url.FullContentUrl("~/images/discord/asm_v2_big.png");
    ViewData["content:center"] = true;
}

<img src="@Url.Content("~/images/discord/asm_v2.png")" alt="ASM" class="bot-image-small" />

<h1>ASM <small>- Documentation</small></h1>

<h3>Help and introduction</h3>

<p class="text-justify">
    The bot uses mention prefix. <code>@@Assembler help</code> displays help.
</p>

<div class="margin">&nbsp;</div>

<h3>Assembling code</h3>

<p class="text-justify">
    <code>@@Assembler assemble &lt;architecture&gt; &lt;code block&gt;</code> assembles code. Architecture can be one of:
</p>

<ul class="list-unstyled text-justify">
    <li>x86: <code>x86 i386 i486 i586 i686</code></li>
    <li>x64: <code>x64 x86_64 amd64</code></li>
    <li>x86 (AT&T syntax): <code>x86_att i386_att i486_att i586_att i686_att</code></li>
    <li>x64 (AT&T syntax): <code>x64_att x86_64_att amd64_att</code></li>
    <li>ARMv6: <code>armv6 armv6k</code></li>
    <li>ARMv6 (big-endian): <code>armv6eb armv6keb armv6_be armv6k_be</code></li>
    <li>ARMv7: <code>armv7 armv7a</code></li>
    <li>ARMv7 (big-endian): <code>armv7eb armv7aeb armv7_be armv7a_be</code></li>
    <li>ARMv8: <code>armv8 armv8a</code></li>
    <li>ARMv8 (big-endian): <code>armv8eb armv8aeb armv8_be armv8a_be</code></li>
    <li>AArch64 (64-bit ARMv8): <code>aarch64 arm64</code></li>
    <li>AArch64 (64-bit ARMv8, big-endian): <code>aarch64eb arm64eb aarch64_be arm64_be</code></li>
    <li>MIPS: <code>mips</code></li>
    <li>MIPS (little-endian): <code>mipsel mips_le</code></li>
    <li>PowerPC: <code>powerpc powerpc32 ppc ppc32</code></li>
    <li>PowerPC64: <code>powerpc64 ppc64</code></li>
    <li>PowerPC64 (little-endian): <code>powerpc64el ppc64el powerpc64_le ppc64_le</code></li>
</ul>

Emzi0767.Web/Views/Discord/CompanionCube.cshtml
@{
    ViewData["Title"] = "Companion Cube";
    ViewData["og:title"] = "Companion Cube";
    ViewData["og:description"] = "Companion Cube is a simple DSharpPlus-based bot. It's primary purpose is to show some of the finer functionality of DSharpPlus in action.";
    ViewData["og:image"] = Url.FullContentUrl("~/images/discord/cc_v1_big.png");
    ViewData["content:center"] = true;
}

<img src="@Url.Content("~/images/discord/cc_v1.png")" alt="Companion Cube" class="bot-image" />

<h1>Companion Cube</h1>

<p>
    Companion Cube is a simple DSharpPlus-based bot. It's primary purpose is to show some of the finer functionality of DSharpPlus in action. On top of that, it offers some basic amenities useful when 
    organizing common information in your server. Among the functionality it offers is tag system, unicode codepoint info, and emoji management. It's very configurable, allows ignoring entire channels, 
    as well as setting prefixes on per-guild basis.
</p>

<div class="margin">&nbsp;</div>

<div class="col-xs-12 col-md-4"><a href="@Url.Action("CompanionCube", new { id = "invite" })" target="_blank" title="Add to your server" class="btn btn-lg btn-primary">Add to your server</a></div>
<div class="col-xs-12 col-md-4"><a href="@Url.Action("CompanionCube", new { id = "doc" })" title="Command documentation" class="btn btn-lg btn-default">Command documentation</a></div>
<div class="col-xs-12 col-md-4"><a href="@Url.Action("CompanionCube", new { id = "source" })" target="_blank" title="View source on GitHub" class="btn btn-lg btn-default">View source on GitHub</a></div>

Emzi0767.Web/Views/Discord/Index.cshtml
@{
    ViewData["Title"] = "Discord";
    ViewData["og:title"] = "Discord";
    ViewData["og:description"] = "A collection of my Discord projects. Here you will also find my other Discord-related information.";
}

<h1>Discord</h1>

<div class="col-xs-12 col-md-8 dontpad">
    <p>
        This is the place to find information about my Discord server and bots. <span class="hidden-xs hidden-sm">On the right</span><span class="hidden-md hidden-lg">Below</span> is the invite to my server.
        Don't hesitate to join if you have any questions or seek information about any of my Discord (or otherwise) projects.
    </p>

    <p>
        Keep in mind that I am based in UTC+1 (or +2 during DST), so you might not get a response when it's middle of the night in that timezone. Other than that, if you behave like a jackass, expect a swift
        resolution in form of a ban.
    </p>

    <p>
        Lastly, my servers offer some emotes to Nitro users. If you join just to take advantage of them, that's fine.
    </p>
</div>
<div class="col-xs-12 col-md-4 content-align-right">
    <a target="_blank" href="https://discord.gg/rGKrJDR" class="discord-server-invite" title="Emzi's Central Dispatch the Discord Server">
        <img src="https://discordapp.com/api/guilds/207879549394878464/embed.png?style=banner1" alt="Discord" />
    </a>
</div>
<div class="clearfix"></div>

<h2>Bots</h2>

<div class="col-xs-12 bot-info">
    <img src="@Url.Content("~/images/discord/cc_v1.png")" alt="Companion Cube" class="bot-avatar bot-avatar-large" />
    <h3>Companion Cube</h3>
    <p>
        Companion Cube is a simple DSharpPlus-based bot. It's primary purpose is to show some of the finer functionality of DSharpPlus in action. On top of that, it offers some basic amenities useful when
        organizing common information in your server.
    </p>
    <p>
        <a href="@Url.Action("CompanionCube")" title="Companion Cube" class="btn btn-primary btn-lg">More information</a>
    </p>
</div>

<div class="col-xs-12 col-md-6 bot-info">
    <img src="@Url.Content("~/images/discord/turret_v1.png")" alt="Music Turret" class="bot-avatar" />
    <h3>Music Turret</h3>
    <p>
        Music Turret was originally part of Companion Cube, however I since split it off into a standalone bot, cleaned it up, and shipped it. The fixes and cleanups were later backported to Companion Cube.
        Turret is a Lavalink-based music bot, with standard music bot features, and some extras. It's only added to servers I trust, and, as such, requires that either I add it, or that you contact me if you 
        want to make use of it.
    </p>
    <p>
        <a href="@Url.Action("MusicTurret")" title="Music Turret" class="btn btn-primary btn-lg">More information</a>
    </p>
</div>

<div class="col-xs-12 col-md-6 bot-info">
    <img src="@Url.Content("~/images/discord/ada_v4.png")" alt="ADA" class="bot-avatar" />
    <h3>ADA</h3>
    <p>
        ADA (Automated/Advanced Discord Administrator) is designed to extend and simplify a number of administrative tasks. It's written in C#, using Discord.NET library. Currently pending porting to Clyde.NET.
    </p>
    <p>
        <a href="@Url.Action("Ada")" title="ADA" class="btn btn-primary btn-lg">More information</a>
    </p>
</div>
<div class="clearfix"></div>

<div class="col-xs-12 col-md-6 bot-info">
    <img src="@Url.Content("~/images/discord/pam_v1.png")" alt="PAM" class="bot-avatar" />
    <h3>PAM</h3>
    <p>
        PAM (Python Administrative Module) is a Python clone of ADA, written using Discord.py library.
    </p>
    <p>
        <a href="@Url.Action("Pam")" title="PAM" class="btn btn-primary btn-lg">More information</a>
    </p>
</div>

<div class="col-xs-12 col-md-6 bot-info">
    <img src="@Url.Content("~/images/discord/asm_v2.png")" alt="ASM" class="bot-avatar" />
    <h3>ASM</h3>
    <p>
        ASM (Assembler) is a bot that assembles assembly code to machine code, and outputs the resulting hex. Written using Discord.py library.
    </p>
    <p>
        <a href="@Url.Action("Asm")" title="ASM" class="btn btn-primary btn-lg">More information</a>
    </p>
</div>

Emzi0767.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<h1>Welcome to Emzi's New Empire</h1>

<p>
    Where I bring peace, freedom, justice, and security.
</p>

<h2>Looking for anything in particular?</h2>

<p>
    Check out the tabs above. In the projects tab you'll find, well, my projects, as well as the projects I contribute to. If you're looking for an app I made, that is your best bet. The only exception is 
    Discord bots, which are in their own tab. The Discord tab also contains information about my server, among other things. Looking to contact me or learn more about me? Check the about me tab.
</p>

<p>
    Looking for something else? Want to donate, perhaps? Check out the footer. It has all the other important information.
</p>

Emzi0767.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1, user-scalable=no" />
    <meta name="description" emzi-description="@ViewData["meta:description"]" emzi-default-description="Emzi0767's personal website. Here you can find information about me, my projects, and more." />
    <meta opengraph-element="Title" opengraph-value="@ViewData["og:title"]" opengraph-default-value="" opengraph-value-suffix="Emzi's New Empire" />
    <meta opengraph-element="Description" opengraph-value="@ViewData["og:description"]" opengraph-default-value="Emzi0767's personal website. Here you can find information about me, my projects, and more. Come if you seek peace, freedom, justice, and security." />
    <meta opengraph-element="Image" opengraph-value="@ViewData["og:image"]" opengraph-default-value="@Url.FullContentUrl("~/images/ogimage.jpg")" />
    <meta opengraph-element="Url" opengraph-value="@ViewData["og:url"]" opengraph-default-value="@Url.Action("Index", "Home", null, Context.Request.Scheme, Context.Request.Host.ToUriComponent())" />
    <meta opengraph-element="Type" opengraph-value="website" opengraph-default-value="website" />
    <title>@ViewData["Title"] - Emzi's New Empire</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <a class="navbar-brand" href="@Url.Action("Index", "Home")" title="Emzi's New Empire - Home Page">
                    <img src="@Url.Content("~/favicon.ico")" alt="Emzi's New Empire" /> Emzi's New Empire
                </a>
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li asp-area="" asp-controller="Home" asp-action="Index" emzi-bootstrap-link="">Home</li>
                    <li asp-area="" asp-controller="Projects" asp-action="Index" emzi-bootstrap-link="" emzi-active-actions="@NavTagHelper.ProjectsActions">Projects</li>
                    <li asp-area="" asp-controller="Discord" asp-action="Index" emzi-bootstrap-link="" emzi-active-actions="@NavTagHelper.DiscordActions">Discord</li>
                    <li asp-area="" asp-controller="Home" asp-action="About" emzi-bootstrap-link="">About me</li>
                </ul>
                <button id="share-btn" class="btn btn-default navbar-btn navbar-right" data-toggle="modal" data-target="#share-modal" title="Share this page">Share</button>
            </div>
        </div>
    </nav>

    <div class="container body-content" emzi-center-content="@(ViewData["content:center"] != null ? (bool)ViewData["content:center"] : false)">
        @RenderBody()
    </div>

    <footer>
        <div class="container">
            <div class="col-xs-12 col-md-9">
                <h5>Be sure to check the links on the right. If you feel like supporting me, you can do so through my Patreon. Any amount is appreciated. I also accept tips in cryptocurrencies.</h5>

                <div class="col-xs-12 col-md-4">
                    <img src="@Url.RouteUrl("api_qr", new { id = ViewData["crypto:eth"].ToBase64(), size = 96 })" class="crypto-qr" /><br>
                    Ethereum<br>
                    <span class="crypto-address">@ViewData["crypto:eth"]</span>
                </div>

                <div class="col-xs-12 col-md-4">
                    <img src="@Url.RouteUrl("api_qr", new { id = ViewData["crypto:btc"].ToBase64(), size = 96 })" class="crypto-qr" /><br>
                    Bitcoin<br>
                    <span class="crypto-address">@ViewData["crypto:btc"]</span>
                </div>

                <div class="col-xs-12 col-md-4">
                    <img src="@Url.RouteUrl("api_qr", new { id = ViewData["crypto:ltc"].ToBase64(), size = 96 })" class="crypto-qr" /><br>
                    Litecoin<br>
                    <span class="crypto-address">@ViewData["crypto:ltc"]</span>
                </div>
            </div>
            <div class="col-xs-12 col-md-3 links">
                <h5>Also check out</h5>

                <ul class="list-unstyled">
                    <li><a target="_blank" href="https://github.com/Emzi0767">My GitHub</a></li>
                    <li><a target="_blank" href="https://paypal.me/Emzi0767">My PayPal</a></li>
                    <li><a target="_blank" href="https://patreon.com/emzi0767">My Patreon</a></li>
                    <li><a target="_blank" href="https://discord.gg/rGKrJDR">My Discord server</a></li>
                    <li><a target="_blank" href="https://bitbucket.org/Emzi0767/emzi0767.com">Source code of this website</a></li>
                </ul>
            </div>
            <div class="copyright col-xs-12">&copy; @DateTimeOffset.UtcNow.Year by Emzi0767</div>
        </div>
    </footer>

    <div class="modal fade" tabindex="-1" role="dialog" id="share-modal">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Share this page</h4>
                </div>
                <div class="modal-body">
                    <img src="@Url.RouteUrl("api_qr", new { id = ViewData["context:url"].ToBase64(), size = 256 })" alt="QR Code for this page" id="qrcode" /><br />
                    <input value="@ViewData["context:url"]" readonly="readonly" class="form-control" />
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.2.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-xBuQ/xzmlsLoJpyjoggmTEz8OWUFM0/RC5BsqQBDX2v5cMvDHcMakNTNrHIW2I5f">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>